#include "src/game/envfx_snow.h"

const GeoLayout castle_inside_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(7, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, castle_inside_dl_BOB_ROOM_geo),
			GEO_BRANCH(1, castle_inside_dl_BOO_HALLWAY_geo),
			GEO_BRANCH(1, castle_inside_dl_CCM_ROOM_geo),
			GEO_BRANCH(1, castle_inside_dl_JRB_ROOM_geo),
			GEO_BRANCH(1, castle_inside_dl_MAIN_ROOM_geo),
			GEO_BRANCH(1, castle_inside_dl_WF_ROOM_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_BOB_ROOM_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 3175, 283, 626, castle_inside_dl_LAYER_ALPHA_inside_castle_seg7_dl_07033158_mesh_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_LAYER_ALPHA_inside_castle_seg7_dl_07033158_mesh_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_inside_dl_LAYER_ALPHA_inside_castle_seg7_dl_07033158_mesh_mesh_layer_6),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_BOO_HALLWAY_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 5186, 0, 3347, castle_inside_dl_LAYER_OPAQUE_inside_castle_seg7_dl_0702E408_mesh_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_CCM_ROOM_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -1332, 275, 4072, castle_inside_dl_LAYER_ALPHA_inside_castle_seg7_dl_0703A808_mesh_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_LAYER_ALPHA_inside_castle_seg7_dl_0703A808_mesh_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_inside_dl_LAYER_ALPHA_inside_castle_seg7_dl_0703A808_mesh_mesh_layer_6),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_JRB_ROOM_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -4355, -293, 924, castle_inside_dl_LAYER_ALPHA_inside_castle_seg7_dl_07038350_mesh_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_LAYER_ALPHA_inside_castle_seg7_dl_07038350_mesh_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_MAIN_ROOM_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_inside_dl_mainroom_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_mainroom_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_inside_dl_mainroom_001_mesh_layer_5_with_revert),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_inside_dl_mainroom_001_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_dl_WF_ROOM_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 1281, -411, 3813, castle_inside_dl_LAYER_OPAQUE_inside_castle_seg7_dl_07034D88_mesh_mesh_layer_1_with_revert),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, castle_inside_dl_LAYER_OPAQUE_inside_castle_seg7_dl_07034D88_mesh_mesh_layer_4_with_revert),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, castle_inside_dl_LAYER_OPAQUE_inside_castle_seg7_dl_07034D88_mesh_mesh_layer_6_with_revert),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_inside_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_inside_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
