// MODIFIED BY A BLENDER ADDON //
#include <PR/ultratypes.h>

#include "dynlist_macros.h"
#include "dynlists.h"
#include "animdata.h"
#include "../dynlist_proc.h"
#include "../shape_helper.h"

struct DynList dynlist_mario_master[1034] = {
    BeginList(),
    UseIntegerNames(TRUE),
    StartGroup(DYNOBJ_MARIO_MAIN_SHAPES_GROUP),
        CallList(dynlist_mario_face_shape),
        CallList(dynlist_mario_eye_right_shape),
        CallList(dynlist_mario_eye_left_shape),
        CallList(dynlist_mario_eyebrow_right_shape),
        CallList(dynlist_mario_eyebrow_left_shape),
        CallList(dynlist_mario_mustache_shape),
    EndGroup(DYNOBJ_MARIO_MAIN_SHAPES_GROUP),
    MakeDynObj(D_LIGHT, DYNOBJ_SILVER_STAR_LIGHT),
    SetId(1),
    SetDiffuse(1.0, 1.0, 1.0),
    SetFlag(32),
    SetShapePtrPtr(&gShapeSilverStar),
    MakeDynObj(D_LIGHT, DYNOBJ_RED_STAR_LIGHT),
    SetId(0),
    SetDiffuse(1.0, 0.0, 0.0),
    SetShapePtrPtr(&gShapeRedStar),
    StartGroup(1),
        MakeDynObj(D_NET, DYNOBJ_MARIO_MAIN_NET),
        SetType(2),
        SetFlag(2),
        SetShapePtr(DYNOBJ_MARIO_FACE_SHAPE),
        SetScale(1.0, 1.0, 1.0),
        SetRotation(112.873, 0.0, 0.0),
        SetAttachOffset(0.0, 0.0, -20010.0),
        MakeNetWithSubGroup(DYNOBJ_RIGHT_EYELID_SKIN_NET),
            AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
            SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
            SetScale(1.0, 1.0, 1.0),
            SetRotation(0.0, 90.0, 0.0),
            SetAttachOffset(116.3, 182.6, -70.2),
            MakeAttachedJoint(DYNOBJ_RIGHT_EYELID_JOINT_1),
            SetScale(1.0, 1.0, 1.0),
            SetRotation(0.0, 0.0, 162.007),
            SetAttachOffset(0.0, 0.0, 0.0),
            SetSkinWeight(7, 94.9999988079071),
            SetSkinWeight(8, 69.9999988079071),
            SetSkinWeight(46, 40.00000059604645),
            SetSkinWeight(47, 10.000000149011612),
            SetSkinWeight(48, 89.99999761581421),
            SetSkinWeight(49, 100.0),
            SetSkinWeight(51, 34.99999940395355),
            SetSkinWeight(82, 10.000000149011612),
            SetSkinWeight(123, 10.000000149011612),
            SetSkinWeight(125, 10.000000149011612),
            SetSkinWeight(126, 5.000000074505806),
            SetSkinWeight(128, 50.0),
            SetSkinWeight(129, 89.99999761581421),
            SetSkinWeight(130, 100.0),
            SetSkinWeight(131, 94.9999988079071),
            SetSkinWeight(132, 69.9999988079071),
            SetSkinWeight(133, 20.000000298023224),
            SetSkinWeight(134, 10.000000149011612),
            SetSkinWeight(420, 34.99999940395355),
            SetSkinWeight(425, 50.0),
            SetSkinWeight(426, 20.000000298023224),
            MakeAttachedJoint(DYNOBJ_RIGHT_EYELID_JOINT_2),
            SetScale(1.0, 1.0, 1.0),
            SetRotation(0.0, 0.0, 0.0),
            SetAttachOffset(382.3, 0.0, 0.0),
            EndNetWithSubGroup(DYNOBJ_RIGHT_EYELID_SKIN_NET),
            MakeNetWithSubGroup(DYNOBJ_LEFT_EYELID_SKIN_NET),
                AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                SetScale(1.0, 1.0, 1.0),
                SetRotation(0.0, 90.0, 0.0),
                SetAttachOffset(-116.3, 182.6, -70.2),
                MakeAttachedJoint(DYNOBJ_LEFT_EYELID_JOINT_1),
                SetScale(1.0, 1.0, 1.0),
                SetRotation(0.0, 0.0, 162.007),
                SetAttachOffset(0.0, 0.0, 0.0),
                SetSkinWeight(194, 89.99999761581421),
                SetSkinWeight(195, 50.0),
                SetSkinWeight(372, 10.000000149011612),
                SetSkinWeight(373, 69.9999988079071),
                SetSkinWeight(383, 5.000000074505806),
                SetSkinWeight(385, 10.000000149011612),
                SetSkinWeight(386, 10.000000149011612),
                SetSkinWeight(387, 10.000000149011612),
                SetSkinWeight(388, 20.000000298023224),
                SetSkinWeight(389, 34.99999940395355),
                SetSkinWeight(390, 69.9999988079071),
                SetSkinWeight(391, 94.9999988079071),
                SetSkinWeight(392, 94.9999988079071),
                SetSkinWeight(393, 100.0),
                SetSkinWeight(394, 100.0),
                SetSkinWeight(395, 10.000000149011612),
                SetSkinWeight(396, 60.00000238418579),
                SetSkinWeight(397, 40.00000059604645),
                SetSkinWeight(416, 34.99999940395355),
                SetSkinWeight(425, 50.0),
                SetSkinWeight(426, 20.000000298023224),
                MakeAttachedJoint(DYNOBJ_LEFT_EYELID_JOINT_2),
                SetScale(1.0, 1.0, 1.0),
                SetRotation(0.0, 0.0, 0.0),
                SetAttachOffset(420.0, 0.0, 0.0),
                EndNetWithSubGroup(DYNOBJ_LEFT_EYELID_SKIN_NET),
                MakeNetWithSubGroup(DYNOBJ_MARIO_JAW_SKIN_NET),
                    AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                    SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                    SetScale(1.0, 1.0, 1.0),
                    SetRotation(0.0, 90.0, 0.0),
                    SetAttachOffset(0.0, -154.9, 118.5),
                    MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_JAW_JOINT),
                    SetScale(1.0, 1.0, 1.0),
                    SetRotation(0.0, 0.0, -111.558),
                    SetAttachOffset(0.0, 0.0, 0.0),
                    SetSkinWeight(4, 30.000001192092896),
                    SetSkinWeight(5, 40.00000059604645),
                    SetSkinWeight(6, 25.0),
                    SetSkinWeight(10, 37.99999952316284),
                    SetSkinWeight(11, 40.00000059604645),
                    SetSkinWeight(16, 2.9999999329447746),
                    SetSkinWeight(17, 2.9999999329447746),
                    SetSkinWeight(34, 2.9999999329447746),
                    SetSkinWeight(35, 5.000000074505806),
                    SetSkinWeight(39, 50.0),
                    SetSkinWeight(85, 69.9999988079071),
                    SetSkinWeight(86, 60.00000238418579),
                    SetSkinWeight(98, 100.0),
                    SetSkinWeight(103, 100.0),
                    SetSkinWeight(104, 50.0),
                    SetSkinWeight(108, 15.000000596046448),
                    SetSkinWeight(109, 5.000000074505806),
                    SetSkinWeight(110, 30.000001192092896),
                    SetSkinWeight(115, 50.0),
                    SetSkinWeight(116, 50.0),
                    SetSkinWeight(157, 50.0),
                    SetSkinWeight(187, 100.0),
                    SetSkinWeight(335, 50.0),
                    SetSkinWeight(353, 15.000000596046448),
                    SetSkinWeight(355, 50.0),
                    SetSkinWeight(356, 100.0),
                    SetSkinWeight(370, 5.000000074505806),
                    SetSkinWeight(371, 2.9999999329447746),
                    SetSkinWeight(374, 5.000000074505806),
                    SetSkinWeight(377, 40.00000059604645),
                    SetSkinWeight(378, 40.00000059604645),
                    SetSkinWeight(379, 2.9999999329447746),
                    SetSkinWeight(381, 2.9999999329447746),
                    SetSkinWeight(402, 37.99999952316284),
                    SetSkinWeight(403, 50.0),
                    SetSkinWeight(404, 25.0),
                    SetSkinWeight(405, 30.000001192092896),
                    SetSkinWeight(406, 30.000001192092896),
                    SetSkinWeight(407, 69.9999988079071),
                    SetSkinWeight(413, 60.00000238418579),
                    MakeAttachedJoint(DYNOBJ_MARIO_LEFT_JAW_JOINT),
                    SetScale(1.0, 1.0, 1.0),
                    SetRotation(0.0, 0.0, -31.153),
                    SetAttachOffset(141.0, 0.0, 0.0),
                    SetSkinWeight(4, 30.000001192092896),
                    SetSkinWeight(5, 40.00000059604645),
                    SetSkinWeight(6, 25.0),
                    SetSkinWeight(10, 37.99999952316284),
                    SetSkinWeight(11, 40.00000059604645),
                    SetSkinWeight(16, 2.9999999329447746),
                    SetSkinWeight(17, 2.9999999329447746),
                    SetSkinWeight(34, 2.9999999329447746),
                    SetSkinWeight(35, 5.000000074505806),
                    SetSkinWeight(39, 50.0),
                    SetSkinWeight(85, 69.9999988079071),
                    SetSkinWeight(86, 60.00000238418579),
                    SetSkinWeight(98, 100.0),
                    SetSkinWeight(103, 100.0),
                    SetSkinWeight(104, 50.0),
                    SetSkinWeight(108, 15.000000596046448),
                    SetSkinWeight(109, 5.000000074505806),
                    SetSkinWeight(110, 30.000001192092896),
                    SetSkinWeight(115, 50.0),
                    SetSkinWeight(116, 50.0),
                    SetSkinWeight(157, 50.0),
                    SetSkinWeight(187, 100.0),
                    SetSkinWeight(335, 50.0),
                    SetSkinWeight(353, 15.000000596046448),
                    SetSkinWeight(355, 50.0),
                    SetSkinWeight(356, 100.0),
                    SetSkinWeight(370, 5.000000074505806),
                    SetSkinWeight(371, 2.9999999329447746),
                    SetSkinWeight(374, 5.000000074505806),
                    SetSkinWeight(377, 40.00000059604645),
                    SetSkinWeight(378, 40.00000059604645),
                    SetSkinWeight(379, 2.9999999329447746),
                    SetSkinWeight(381, 2.9999999329447746),
                    SetSkinWeight(402, 37.99999952316284),
                    SetSkinWeight(403, 50.0),
                    SetSkinWeight(404, 25.0),
                    SetSkinWeight(405, 30.000001192092896),
                    SetSkinWeight(406, 30.000001192092896),
                    SetSkinWeight(407, 69.9999988079071),
                    SetSkinWeight(413, 60.00000238418579),
                    MakeAttachedJoint(DYNOBJ_MARIO_UNKNOWN_191),
                    SetScale(1.0, 1.0, 1.0),
                    SetRotation(0.0, 0.0, 0.0),
                    SetAttachOffset(80.1, 0.0, 0.0),
                    EndNetWithSubGroup(DYNOBJ_MARIO_JAW_SKIN_NET),
                    MakeNetWithSubGroup(DYNOBJ_MARIO_NOSE_SKIN_NET),
                        AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                        SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                        SetScale(1.0, 1.0, 1.0),
                        SetRotation(0.0, 90.0, 0.0),
                        SetAttachOffset(0.0, 15.3, 295.1),
                        MakeAttachedJoint(DYNOBJ_MARIO_NOSE_JOINT_1),
                        SetScale(1.0, 1.0, 1.0),
                        SetRotation(0.0, 0.0, -178.586),
                        SetAttachOffset(0.0, 0.0, 0.0),
                        SetSkinWeight(15, 5.000000074505806),
                        SetSkinWeight(18, 30.000001192092896),
                        SetSkinWeight(19, 40.00000059604645),
                        SetSkinWeight(20, 5.000000074505806),
                        SetSkinWeight(21, 5.000000074505806),
                        SetSkinWeight(22, 30.000001192092896),
                        SetSkinWeight(23, 69.9999988079071),
                        SetSkinWeight(24, 40.00000059604645),
                        SetSkinWeight(25, 89.99999761581421),
                        SetSkinWeight(26, 69.9999988079071),
                        SetSkinWeight(27, 89.99999761581421),
                        SetSkinWeight(28, 40.00000059604645),
                        SetSkinWeight(29, 69.9999988079071),
                        SetSkinWeight(30, 89.99999761581421),
                        SetSkinWeight(41, 69.9999988079071),
                        SetSkinWeight(82, 5.000000074505806),
                        SetSkinWeight(83, 5.000000074505806),
                        SetSkinWeight(87, 5.000000074505806),
                        SetSkinWeight(158, 69.9999988079071),
                        SetSkinWeight(159, 100.0),
                        SetSkinWeight(180, 89.99999761581421),
                        SetSkinWeight(181, 89.99999761581421),
                        SetSkinWeight(344, 69.9999988079071),
                        SetSkinWeight(345, 30.000001192092896),
                        SetSkinWeight(346, 69.9999988079071),
                        SetSkinWeight(347, 40.00000059604645),
                        SetSkinWeight(348, 30.000001192092896),
                        SetSkinWeight(349, 69.9999988079071),
                        SetSkinWeight(350, 89.99999761581421),
                        SetSkinWeight(351, 5.000000074505806),
                        SetSkinWeight(382, 5.000000074505806),
                        SetSkinWeight(384, 5.000000074505806),
                        SetSkinWeight(385, 5.000000074505806),
                        SetSkinWeight(427, 69.9999988079071),
                        SetSkinWeight(428, 69.9999988079071),
                        SetSkinWeight(429, 40.00000059604645),
                        SetSkinWeight(430, 69.9999988079071),
                        SetSkinWeight(431, 69.9999988079071),
                        SetSkinWeight(432, 69.9999988079071),
                        SetSkinWeight(433, 69.9999988079071),
                        SetSkinWeight(434, 69.9999988079071),
                        SetSkinWeight(435, 40.00000059604645),
                        SetSkinWeight(436, 69.9999988079071),
                        MakeAttachedJoint(DYNOBJ_MARIO_NOSE_JOINT_2),
                        SetScale(1.0, 1.0, 1.0),
                        SetRotation(0.0, 0.0, 0.0),
                        SetAttachOffset(276.6, 0.0, 0.0),
                        EndNetWithSubGroup(DYNOBJ_MARIO_NOSE_SKIN_NET),
                        MakeNetWithSubGroup(DYNOBJ_MARIO_RIGHT_EAR_SKIN_NET),
                            AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                            SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                            SetScale(1.0, 1.0, 1.0),
                            SetRotation(-90.0, 0.0, 0.0),
                            SetAttachOffset(294.7, 13.1, -82.1),
                            MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_EAR_JOINT_1),
                            SetScale(1.0, 1.0, 1.0),
                            SetRotation(0.0, 0.0, 26.565),
                            SetAttachOffset(0.0, 0.0, 0.0),
                            SetSkinWeight(59, 80.0000011920929),
                            SetSkinWeight(60, 50.0),
                            SetSkinWeight(61, 60.00000238418579),
                            SetSkinWeight(65, 100.0),
                            SetSkinWeight(66, 60.00000238418579),
                            SetSkinWeight(88, 10.000000149011612),
                            SetSkinWeight(89, 60.00000238418579),
                            SetSkinWeight(90, 80.0000011920929),
                            SetSkinWeight(91, 69.9999988079071),
                            SetSkinWeight(92, 100.0),
                            SetSkinWeight(117, 15.000000596046448),
                            SetSkinWeight(118, 5.000000074505806),
                            SetSkinWeight(119, 15.000000596046448),
                            SetSkinWeight(121, 60.00000238418579),
                            SetSkinWeight(122, 69.9999988079071),
                            SetSkinWeight(135, 10.000000149011612),
                            SetSkinWeight(136, 60.00000238418579),
                            SetSkinWeight(137, 10.000000149011612),
                            SetSkinWeight(138, 5.000000074505806),
                            SetSkinWeight(139, 10.000000149011612),
                            SetSkinWeight(165, 60.00000238418579),
                            SetSkinWeight(166, 69.9999988079071),
                            SetSkinWeight(222, 50.0),
                            SetSkinWeight(223, 69.9999988079071),
                            SetSkinWeight(224, 50.0),
                            SetSkinWeight(225, 50.0),
                            SetSkinWeight(226, 60.00000238418579),
                            SetSkinWeight(227, 60.00000238418579),
                            SetSkinWeight(233, 10.000000149011612),
                            MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_EAR_JOINT_2),
                            SetScale(1.0, 1.0, 1.0),
                            SetRotation(0.0, 0.0, 0.0),
                            SetAttachOffset(200.9, 0.0, 0.0),
                            EndNetWithSubGroup(DYNOBJ_MARIO_RIGHT_EAR_SKIN_NET),
                            MakeNetWithSubGroup(DYNOBJ_MARIO_LEFT_EAR_SKIN_NET),
                                AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                                SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                                SetScale(1.0, 1.0, 1.0),
                                SetRotation(90.0, 180.0, 0.0),
                                SetAttachOffset(-294.7, 13.1, -82.1),
                                MakeAttachedJoint(DYNOBJ_MARIO_LEFT_EAR_JOINT_1),
                                SetScale(1.0, 1.0, 1.0),
                                SetRotation(180.0, 180.0, -153.435),
                                SetAttachOffset(0.0, 0.0, 0.0),
                                SetSkinWeight(242, 5.000000074505806),
                                SetSkinWeight(265, 5.000000074505806),
                                SetSkinWeight(266, 5.000000074505806),
                                SetSkinWeight(297, 5.000000074505806),
                                SetSkinWeight(300, 5.000000074505806),
                                SetSkinWeight(305, 69.9999988079071),
                                SetSkinWeight(306, 69.9999988079071),
                                SetSkinWeight(307, 100.0),
                                SetSkinWeight(308, 69.9999988079071),
                                SetSkinWeight(309, 69.9999988079071),
                                SetSkinWeight(312, 100.0),
                                SetSkinWeight(313, 69.9999988079071),
                                SetSkinWeight(315, 80.0000011920929),
                                SetSkinWeight(316, 69.9999988079071),
                                SetSkinWeight(317, 80.0000011920929),
                                SetSkinWeight(318, 69.9999988079071),
                                SetSkinWeight(319, 10.000000149011612),
                                SetSkinWeight(320, 10.000000149011612),
                                SetSkinWeight(321, 10.000000149011612),
                                SetSkinWeight(322, 10.000000149011612),
                                SetSkinWeight(323, 60.00000238418579),
                                SetSkinWeight(324, 100.0),
                                SetSkinWeight(325, 100.0),
                                SetSkinWeight(326, 100.0),
                                SetSkinWeight(327, 80.0000011920929),
                                SetSkinWeight(328, 80.0000011920929),
                                SetSkinWeight(329, 60.00000238418579),
                                SetSkinWeight(330, 69.9999988079071),
                                SetSkinWeight(338, 69.9999988079071),
                                MakeAttachedJoint(DYNOBJ_MARIO_LEFT_EAR_JOINT_2),
                                SetScale(1.0, 1.0, 1.0),
                                SetRotation(0.0, 0.0, 0.02),
                                SetAttachOffset(200.9, 0.0, 0.0),
                                EndNetWithSubGroup(DYNOBJ_MARIO_LEFT_EAR_SKIN_NET),
                                MakeNetWithSubGroup(DYNOBJ_MARIO_RIGHT_LIP_CORNER_SKIN_NET),
                                    AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                                    SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                                    SetScale(1.0, 1.0, 1.0),
                                    SetRotation(-90.0, 0.0, 0.0),
                                    SetAttachOffset(119.7, -161.4, 125.5),
                                    MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_LIP_CORNER_JOINT_1),
                                    SetScale(1.0, 1.0, 1.0),
                                    SetRotation(-0.02, 0.0, -66.509),
                                    SetAttachOffset(0.0, 0.0, 0.0),
                                    SetSkinWeight(4, 41.999998688697815),
                                    SetSkinWeight(5, 40.00000059604645),
                                    SetSkinWeight(6, 75.0),
                                    SetSkinWeight(10, 30.000001192092896),
                                    SetSkinWeight(11, 40.00000059604645),
                                    SetSkinWeight(16, 20.000000298023224),
                                    SetSkinWeight(17, 15.000000596046448),
                                    SetSkinWeight(31, 20.000000298023224),
                                    SetSkinWeight(32, 20.000000298023224),
                                    SetSkinWeight(33, 30.000001192092896),
                                    SetSkinWeight(34, 20.000000298023224),
                                    SetSkinWeight(35, 60.00000238418579),
                                    SetSkinWeight(37, 10.000000149011612),
                                    SetSkinWeight(42, 30.000001192092896),
                                    SetSkinWeight(43, 40.00000059604645),
                                    SetSkinWeight(44, 15.000000596046448),
                                    SetSkinWeight(85, 30.000001192092896),
                                    SetSkinWeight(86, 30.000001192092896),
                                    SetSkinWeight(93, 30.000001192092896),
                                    SetSkinWeight(94, 10.000000149011612),
                                    SetSkinWeight(100, 100.0),
                                    SetSkinWeight(101, 30.000001192092896),
                                    SetSkinWeight(102, 100.0),
                                    SetSkinWeight(107, 10.000000149011612),
                                    SetSkinWeight(108, 69.9999988079071),
                                    SetSkinWeight(109, 80.0000011920929),
                                    SetSkinWeight(110, 60.00000238418579),
                                    SetSkinWeight(111, 69.9999988079071),
                                    SetSkinWeight(157, 50.0),
                                    MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_LIP_CORNER_JOINT_2),
                                    SetScale(1.0, 1.0, 1.0),
                                    SetRotation(0.028, 0.0, 0.0),
                                    SetAttachOffset(184.5, 0.0, 0.0),
                                    EndNetWithSubGroup(DYNOBJ_MARIO_RIGHT_LIP_CORNER_SKIN_NET),
                                    MakeNetWithSubGroup(DYNOBJ_MARIO_LEFT_LIP_CORNER_SKIN_NET),
                                        AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                                        SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                                        SetScale(1.0, 1.0, 1.0),
                                        SetRotation(90.0, 180.0, 0.0),
                                        SetAttachOffset(-119.7, -161.4, 125.5),
                                        MakeAttachedJoint(DYNOBJ_MARIO_LEFT_LIP_CORNER_JOINT_1),
                                        SetScale(1.0, 1.0, 1.0),
                                        SetRotation(0.02, 0.0, -66.509),
                                        SetAttachOffset(0.0, 0.0, 0.0),
                                        SetSkinWeight(185, 100.0),
                                        SetSkinWeight(186, 20.000000298023224),
                                        SetSkinWeight(196, 20.000000298023224),
                                        SetSkinWeight(197, 15.000000596046448),
                                        SetSkinWeight(271, 30.000001192092896),
                                        SetSkinWeight(340, 10.000000149011612),
                                        SetSkinWeight(352, 40.00000059604645),
                                        SetSkinWeight(353, 69.9999988079071),
                                        SetSkinWeight(354, 69.9999988079071),
                                        SetSkinWeight(355, 50.0),
                                        SetSkinWeight(369, 10.000000149011612),
                                        SetSkinWeight(370, 60.00000238418579),
                                        SetSkinWeight(371, 20.000000298023224),
                                        SetSkinWeight(374, 80.0000011920929),
                                        SetSkinWeight(375, 100.0),
                                        SetSkinWeight(376, 10.000000149011612),
                                        SetSkinWeight(377, 40.00000059604645),
                                        SetSkinWeight(378, 30.000001192092896),
                                        SetSkinWeight(379, 15.000000596046448),
                                        SetSkinWeight(381, 20.000000298023224),
                                        SetSkinWeight(401, 30.000001192092896),
                                        SetSkinWeight(402, 30.000001192092896),
                                        SetSkinWeight(404, 75.0),
                                        SetSkinWeight(405, 60.00000238418579),
                                        SetSkinWeight(406, 41.999998688697815),
                                        SetSkinWeight(407, 30.000001192092896),
                                        SetSkinWeight(408, 20.000000298023224),
                                        SetSkinWeight(412, 20.000000298023224),
                                        SetSkinWeight(413, 36.000001430511475),
                                        MakeAttachedJoint(DYNOBJ_MARIO_LEFT_LIP_CORNER_JOINT_2),
                                        SetScale(1.0, 1.0, 1.0),
                                        SetRotation(-0.028, 0.0, 0.0),
                                        SetAttachOffset(184.5, 0.0, 0.0),
                                        EndNetWithSubGroup(DYNOBJ_MARIO_LEFT_LIP_CORNER_SKIN_NET),
                                        MakeNetWithSubGroup(143),
                                            AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                                            SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                                            SetScale(1.0, 1.0, 1.0),
                                            SetRotation(0.0, 90.0, 0.0),
                                            SetAttachOffset(0.0, -162.2, 121.0),
                                            MakeAttachedJoint(DYNOBJ_MARIO_UNKNOWN_140),
                                            SetScale(1.0, 1.0, 1.0),
                                            SetRotation(0.0, 0.0, -176.775),
                                            SetAttachOffset(0.0, 0.0, 0.0),
                                            SetSkinWeight(42, 69.9999988079071),
                                            SetSkinWeight(44, 85.00000238418579),
                                            SetSkinWeight(101, 69.9999988079071),
                                            SetSkinWeight(186, 80.0000011920929),
                                            SetSkinWeight(196, 80.0000011920929),
                                            SetSkinWeight(197, 85.00000238418579),
                                            MakeAttachedJoint(DYNOBJ_MARIO_UNKNOWN_137),
                                            SetScale(1.0, 1.0, 1.0),
                                            SetRotation(0.0, 0.0, 0.0),
                                            SetAttachOffset(242.8, 0.0, 0.0),
                                            EndNetWithSubGroup(143),
                                            MakeNetWithSubGroup(DYNOBJ_MARIO_CAP_SKIN_NET),
                                                AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                                                SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                                                SetScale(1.0, 1.0, 1.0),
                                                SetRotation(0.0, 90.0, 0.0),
                                                SetAttachOffset(0.0, 233.8, -148.8),
                                                MakeAttachedJoint(DYNOBJ_MARIO_CAP_JOINT_1),
                                                SetScale(1.0, 1.0, 1.0),
                                                SetRotation(0.0, 0.0, 153.932),
                                                SetAttachOffset(0.0, 0.0, 0.0),
                                                SetSkinWeight(0, 100.0),
                                                SetSkinWeight(1, 100.0),
                                                SetSkinWeight(2, 80.0000011920929),
                                                SetSkinWeight(9, 100.0),
                                                SetSkinWeight(50, 100.0),
                                                SetSkinWeight(54, 100.0),
                                                SetSkinWeight(55, 100.0),
                                                SetSkinWeight(56, 100.0),
                                                SetSkinWeight(57, 100.0),
                                                SetSkinWeight(58, 100.0),
                                                SetSkinWeight(67, 80.0000011920929),
                                                SetSkinWeight(68, 89.99999761581421),
                                                SetSkinWeight(69, 100.0),
                                                SetSkinWeight(70, 100.0),
                                                SetSkinWeight(71, 100.0),
                                                SetSkinWeight(75, 100.0),
                                                SetSkinWeight(76, 100.0),
                                                SetSkinWeight(77, 100.0),
                                                SetSkinWeight(78, 89.99999761581421),
                                                SetSkinWeight(79, 80.0000011920929),
                                                SetSkinWeight(80, 100.0),
                                                SetSkinWeight(120, 100.0),
                                                SetSkinWeight(124, 60.00000238418579),
                                                SetSkinWeight(127, 100.0),
                                                SetSkinWeight(140, 50.0),
                                                SetSkinWeight(141, 50.0),
                                                SetSkinWeight(143, 80.0000011920929),
                                                SetSkinWeight(144, 100.0),
                                                SetSkinWeight(145, 89.99999761581421),
                                                SetSkinWeight(146, 89.99999761581421),
                                                SetSkinWeight(147, 100.0),
                                                SetSkinWeight(148, 100.0),
                                                SetSkinWeight(149, 100.0),
                                                SetSkinWeight(150, 89.99999761581421),
                                                SetSkinWeight(152, 100.0),
                                                SetSkinWeight(153, 100.0),
                                                SetSkinWeight(154, 100.0),
                                                SetSkinWeight(155, 100.0),
                                                SetSkinWeight(156, 89.99999761581421),
                                                SetSkinWeight(182, 100.0),
                                                SetSkinWeight(183, 100.0),
                                                SetSkinWeight(184, 100.0),
                                                SetSkinWeight(190, 100.0),
                                                SetSkinWeight(191, 89.99999761581421),
                                                SetSkinWeight(192, 80.0000011920929),
                                                SetSkinWeight(193, 100.0),
                                                SetSkinWeight(199, 100.0),
                                                SetSkinWeight(200, 100.0),
                                                SetSkinWeight(228, 100.0),
                                                SetSkinWeight(237, 50.0),
                                                SetSkinWeight(238, 80.0000011920929),
                                                SetSkinWeight(240, 100.0),
                                                SetSkinWeight(243, 50.0),
                                                SetSkinWeight(244, 100.0),
                                                SetSkinWeight(245, 100.0),
                                                SetSkinWeight(246, 50.0),
                                                SetSkinWeight(247, 89.99999761581421),
                                                SetSkinWeight(249, 100.0),
                                                SetSkinWeight(268, 50.0),
                                                SetSkinWeight(292, 60.00000238418579),
                                                SetSkinWeight(301, 89.99999761581421),
                                                SetSkinWeight(302, 100.0),
                                                SetSkinWeight(303, 100.0),
                                                SetSkinWeight(304, 100.0),
                                                SetSkinWeight(333, 100.0),
                                                SetSkinWeight(336, 100.0),
                                                SetSkinWeight(343, 100.0),
                                                SetSkinWeight(357, 89.99999761581421),
                                                SetSkinWeight(358, 100.0),
                                                SetSkinWeight(359, 100.0),
                                                SetSkinWeight(360, 100.0),
                                                SetSkinWeight(361, 100.0),
                                                SetSkinWeight(362, 100.0),
                                                SetSkinWeight(363, 100.0),
                                                SetSkinWeight(364, 100.0),
                                                SetSkinWeight(365, 89.99999761581421),
                                                SetSkinWeight(366, 100.0),
                                                SetSkinWeight(367, 89.99999761581421),
                                                SetSkinWeight(368, 80.0000011920929),
                                                SetSkinWeight(398, 100.0),
                                                SetSkinWeight(399, 100.0),
                                                SetSkinWeight(400, 100.0),
                                                SetSkinWeight(414, 80.0000011920929),
                                                SetSkinWeight(417, 100.0),
                                                SetSkinWeight(418, 100.0),
                                                SetSkinWeight(419, 100.0),
                                                SetSkinWeight(421, 100.0),
                                                SetSkinWeight(422, 100.0),
                                                SetSkinWeight(423, 100.0),
                                                SetSkinWeight(424, 100.0),
                                                MakeAttachedJoint(DYNOBJ_MARIO_CAP_JOINT_2),
                                                SetScale(1.0, 1.0, 1.0),
                                                SetRotation(0.0, 0.0, 0.0),
                                                SetAttachOffset(528.3, 0.0, 0.0),
                                                EndNetWithSubGroup(DYNOBJ_MARIO_CAP_SKIN_NET),
                                                MakeNetWithSubGroup(DYNOBJ_MARIO_RIGHT_EYE_SKIN_NET),
                                                    AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                                                    SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                                                    SetScale(1.0, 1.0, 1.0),
                                                    SetRotation(90.0, 180.0, 0.0),
                                                    SetAttachOffset(29.7, 192.4, -3.0),
                                                    MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_EYE_JOINT_1),
                                                    SetScale(1.0, 1.0, 1.0),
                                                    SetRotation(184.483, -178.885, 82.485),
                                                    SetAttachOffset(0.0, 0.0, 0.0),
                                                    MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_EYE_JOINT_2),
                                                    SetScale(1.0, 1.0, 1.0),
                                                    SetRotation(0.0, 0.0, 0.0),
                                                    SetAttachOffset(329.8, 0.0, 0.0),
                                                    EndNetWithSubGroup(DYNOBJ_MARIO_RIGHT_EYE_SKIN_NET),
                                                    MakeDynObj(D_NET, DYNOBJ_MARIO_RIGHT_EYE_UNKNOWN_NET),
                                                    SetType(3),
                                                    SetShapePtr(DYNOBJ_MARIO_RIGHT_EYE_SHAPE),
                                                    AttachTo(13, DYNOBJ_MARIO_RIGHT_EYE_JOINT_1),
                                                    SetScale(1.0, 1.0, 1.0),
                                                    SetRotation(0.0, 0.0, 0.0),
                                                    SetAttachOffset(0.0, 0.0, 0.0),
                                                    MakeNetWithSubGroup(DYNOBJ_MARIO_LEFT_EYE_SKIN_NET),
                                                        AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                                                        SetSkinShape(DYNOBJ_MARIO_FACE_SHAPE),
                                                        SetScale(1.0, 1.0, 1.0),
                                                        SetRotation(-90.0, 0.0, 0.0),
                                                        SetAttachOffset(-29.0, 192.3, -2.0),
                                                        MakeAttachedJoint(DYNOBJ_MARIO_LEFT_EYE_JOINT_1),
                                                        SetScale(1.0, 1.0, 1.0),
                                                        SetRotation(-6.873, 0.206, -97.461),
                                                        SetAttachOffset(0.0, 0.0, 0.0),
                                                        SetSkinWeight(426, 15.999999642372131),
                                                        MakeAttachedJoint(DYNOMJ_MARIO_LEFT_EYE_JOINT_2),
                                                        SetScale(1.0, 1.0, 1.0),
                                                        SetRotation(0.0, 0.0, 0.0),
                                                        SetAttachOffset(329.8, 0.0, 0.0),
                                                        EndNetWithSubGroup(DYNOBJ_MARIO_LEFT_EYE_SKIN_NET),
                                                        MakeDynObj(D_NET, DYNOBJ_MARIO_LEFT_EYE_UNKNOWN_NET),
                                                        SetType(3),
                                                        SetShapePtr(DYNOBJ_MARIO_LEFT_EYE_SHAPE),
                                                        AttachTo(13, DYNOBJ_MARIO_LEFT_EYE_JOINT_1),
                                                        SetScale(1.0, 1.0, 1.0),
                                                        SetRotation(0.0, 0.0, 0.0),
                                                        SetAttachOffset(0.0, 0.0, 0.0),
                                                        MakeDynObj(D_NET, DYNOBJ_MARIO_RIGHT_EYEBROW_NET),
                                                        SetType(2),
                                                        SetShapePtr(DYNOBJ_MARIO_RIGHT_EYEBROW_SHAPE),
                                                        AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                                                        SetScale(1.0, 1.0, 1.0),
                                                        SetRotation(0.0, 0.0, 0.0),
                                                        SetAttachOffset(20.8, 0.0, -8.5),
                                                        MakeNetWithSubGroup(DYNOBJ_MARIO_RIGHT_EYEBROW_RPART_SKIN_NET),
                                                            AttachTo(13, DYNOBJ_MARIO_RIGHT_EYEBROW_NET),
                                                            SetSkinShape(DYNOBJ_MARIO_RIGHT_EYEBROW_SHAPE),
                                                            SetScale(1.0, 1.0, 1.0),
                                                            SetRotation(-90.0, 90.0, -90.0),
                                                            SetAttachOffset(231.3, 287.1, -51.4),
                                                            MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_EYEBROW_RPART_JOINT_1),
                                                            SetScale(1.0, 1.0, 1.0),
                                                            SetRotation(10.886, 0.0, 177.51),
                                                            SetAttachOffset(0.0, 0.0, 0.0),
                                                            SetSkinWeight(5, 69.9999988079071),
                                                            SetSkinWeight(6, 80.0000011920929),
                                                            SetSkinWeight(7, 69.9999988079071),
                                                            SetSkinWeight(8, 50.0),
                                                            SetSkinWeight(11, 69.9999988079071),
                                                            SetSkinWeight(12, 100.0),
                                                            SetSkinWeight(19, 50.0),
                                                            SetSkinWeight(20, 80.0000011920929),
                                                            SetSkinWeight(23, 69.9999988079071),
                                                            MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_EYEBROW_RPART_JOINT_2),
                                                            SetScale(1.0, 1.0, 1.0),
                                                            SetRotation(0.0, 0.0, 0.0),
                                                            SetAttachOffset(345.5, 0.0, 0.0),
                                                            EndNetWithSubGroup(DYNOBJ_MARIO_RIGHT_EYEBROW_RPART_SKIN_NET),
                                                            MakeNetWithSubGroup(DYNOBJ_MARIO_RIGHT_EYEBROW_LPART_SKIN_NET),
                                                                AttachTo(13, DYNOBJ_MARIO_RIGHT_EYEBROW_NET),
                                                                SetSkinShape(DYNOBJ_MARIO_RIGHT_EYEBROW_SHAPE),
                                                                SetScale(1.0, 1.0, 1.0),
                                                                SetRotation(-90.0, 90.0, -90.0),
                                                                SetAttachOffset(23.0, 305.5, -44.6),
                                                                MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_EYEBROW_LPART_JOINT_1),
                                                                SetScale(1.0, 1.0, 1.0),
                                                                SetRotation(-3.437, -0.069, -177.758),
                                                                SetAttachOffset(0.0, 0.0, 0.0),
                                                                SetSkinWeight(15, 30.000001192092896),
                                                                SetSkinWeight(16, 80.0000011920929),
                                                                SetSkinWeight(17, 100.0),
                                                                SetSkinWeight(18, 80.0000011920929),
                                                                SetSkinWeight(22, 69.9999988079071),
                                                                SetSkinWeight(24, 50.0),
                                                                SetSkinWeight(25, 80.0000011920929),
                                                                MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_EYEBROW_LPART_JOINT_2),
                                                                SetScale(1.0, 1.0, 1.0),
                                                                SetRotation(0.0, 0.0, 0.0),
                                                                SetAttachOffset(399.5, 0.0, 0.0),
                                                                EndNetWithSubGroup(DYNOBJ_MARIO_RIGHT_EYEBROW_LPART_SKIN_NET),
                                                                MakeNetWithSubGroup(DYNOBJ_MARIO_RIGHT_EYEBROW_MPART_SKIN_NET),
                                                                    AttachTo(13, DYNOBJ_MARIO_RIGHT_EYEBROW_NET),
                                                                    SetSkinShape(DYNOBJ_MARIO_RIGHT_EYEBROW_SHAPE),
                                                                    SetScale(1.0, 1.0, 1.0),
                                                                    SetRotation(-90.0, 90.0, -90.0),
                                                                    SetAttachOffset(123.1, 385.5, -46.4),
                                                                    MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_EYEBROW_MPART_JOINT_1),
                                                                    SetScale(1.0, 1.0, 1.0),
                                                                    SetRotation(2.865, 0.029, 182.377),
                                                                    SetAttachOffset(0.0, 0.0, 0.0),
                                                                    SetSkinWeight(0, 100.0),
                                                                    SetSkinWeight(1, 100.0),
                                                                    SetSkinWeight(2, 100.0),
                                                                    SetSkinWeight(3, 100.0),
                                                                    SetSkinWeight(4, 100.0),
                                                                    SetSkinWeight(5, 30.000001192092896),
                                                                    SetSkinWeight(6, 20.000000298023224),
                                                                    SetSkinWeight(7, 30.000001192092896),
                                                                    SetSkinWeight(8, 50.0),
                                                                    SetSkinWeight(9, 100.0),
                                                                    SetSkinWeight(10, 100.0),
                                                                    SetSkinWeight(11, 30.000001192092896),
                                                                    SetSkinWeight(13, 100.0),
                                                                    SetSkinWeight(14, 100.0),
                                                                    SetSkinWeight(15, 69.9999988079071),
                                                                    SetSkinWeight(16, 20.000000298023224),
                                                                    SetSkinWeight(18, 20.000000298023224),
                                                                    SetSkinWeight(19, 50.0),
                                                                    SetSkinWeight(20, 20.000000298023224),
                                                                    SetSkinWeight(21, 100.0),
                                                                    SetSkinWeight(22, 30.000001192092896),
                                                                    SetSkinWeight(23, 30.000001192092896),
                                                                    SetSkinWeight(24, 50.0),
                                                                    SetSkinWeight(25, 20.000000298023224),
                                                                    MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_EYEBROW_MPART_JOINT_2),
                                                                    SetScale(1.0, 1.0, 1.0),
                                                                    SetRotation(0.0, 0.0, 0.0),
                                                                    SetAttachOffset(388.6, 0.0, 0.0),
                                                                    EndNetWithSubGroup(DYNOBJ_MARIO_RIGHT_EYEBROW_MPART_SKIN_NET),
                                                                    MakeDynObj(D_NET, DYNOBJ_MARIO_LEFT_EYEBROW_NET),
                                                                    SetType(2),
                                                                    SetShapePtr(DYNOBJ_MARIO_LEFT_EYEBROW_SHAPE),
                                                                    AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                                                                    SetScale(1.0, 1.0, 1.0),
                                                                    SetRotation(0.0, 0.0, 0.0),
                                                                    SetAttachOffset(-18.5, 0.0, -1.0),
                                                                    MakeNetWithSubGroup(DYNOBJ_MARIO_LEFT_EYEBROW_LPART_SKIN_NET),
                                                                        AttachTo(13, DYNOBJ_MARIO_LEFT_EYEBROW_NET),
                                                                        SetSkinShape(DYNOBJ_MARIO_LEFT_EYEBROW_SHAPE),
                                                                        SetScale(1.0, 1.0, 1.0),
                                                                        SetRotation(0.0, 90.0, 0.0),
                                                                        SetAttachOffset(-233.6, 287.1, -51.4),
                                                                        MakeAttachedJoint(DYNOBJ_MARIO_LEFT_EYEBROW_LPART_JOINT_1),
                                                                        SetScale(1.0, 1.0, 1.0),
                                                                        SetRotation(-6.876, 0.0, 177.51),
                                                                        SetAttachOffset(0.0, 0.0, 0.0),
                                                                        SetSkinWeight(9, 100.0),
                                                                        SetSkinWeight(10, 80.0000011920929),
                                                                        SetSkinWeight(11, 80.0000011920929),
                                                                        SetSkinWeight(13, 80.0000011920929),
                                                                        SetSkinWeight(14, 80.0000011920929),
                                                                        SetSkinWeight(18, 60.00000238418579),
                                                                        SetSkinWeight(21, 60.00000238418579),
                                                                        SetSkinWeight(25, 60.00000238418579),
                                                                        MakeAttachedJoint(DYNOBJ_MARIO_LEFT_EYEBROW_LPART_JOINT_2),
                                                                        SetScale(1.0, 1.0, 1.0),
                                                                        SetRotation(0.0, 0.0, 0.0),
                                                                        SetAttachOffset(345.5, 0.0, 0.0),
                                                                        EndNetWithSubGroup(DYNOBJ_MARIO_LEFT_EYEBROW_LPART_SKIN_NET),
                                                                        MakeNetWithSubGroup(DYNOBJ_MARIO_LEFT_EYEBROW_RPART_SKIN_NET),
                                                                            AttachTo(13, DYNOBJ_MARIO_LEFT_EYEBROW_NET),
                                                                            SetSkinShape(DYNOBJ_MARIO_LEFT_EYEBROW_SHAPE),
                                                                            SetScale(1.0, 1.0, 1.0),
                                                                            SetRotation(0.0, 90.0, 0.0),
                                                                            SetAttachOffset(-25.3, 305.5, -44.6),
                                                                            MakeAttachedJoint(DYNOBJ_MARIO_LEFT_EYEBROW_RPART_JOINT_1),
                                                                            SetScale(1.0, 1.0, 1.0),
                                                                            SetRotation(-9.733, -0.388, -177.186),
                                                                            SetAttachOffset(0.0, 0.0, 0.0),
                                                                            SetSkinWeight(0, 69.9999988079071),
                                                                            SetSkinWeight(1, 100.0),
                                                                            SetSkinWeight(2, 69.9999988079071),
                                                                            SetSkinWeight(3, 69.9999988079071),
                                                                            SetSkinWeight(5, 50.0),
                                                                            SetSkinWeight(12, 69.9999988079071),
                                                                            SetSkinWeight(15, 30.000001192092896),
                                                                            SetSkinWeight(19, 30.000001192092896),
                                                                            MakeAttachedJoint(DYNOBJ_MARIO_LEFT_EYEBROW_RPART_JOINT_2),
                                                                            SetScale(1.0, 1.0, 1.0),
                                                                            SetRotation(0.0, 0.0, 0.0),
                                                                            SetAttachOffset(399.5, 0.0, 0.0),
                                                                            EndNetWithSubGroup(DYNOBJ_MARIO_LEFT_EYEBROW_RPART_SKIN_NET),
                                                                            MakeNetWithSubGroup(DYNOBJ_MARIO_LEFT_EYEBROW_MPART_SKIN_NET),
                                                                                AttachTo(13, DYNOBJ_MARIO_LEFT_EYEBROW_NET),
                                                                                SetSkinShape(DYNOBJ_MARIO_LEFT_EYEBROW_SHAPE),
                                                                                SetScale(1.0, 1.0, 1.0),
                                                                                SetRotation(0.0, 90.0, 0.0),
                                                                                SetAttachOffset(-125.4, 385.5, -46.4),
                                                                                MakeAttachedJoint(DYNOBJ_MARIO_LEFT_EYEBROW_MPART_JOINT_1),
                                                                                SetScale(1.0, 1.0, 1.0),
                                                                                SetRotation(-8.004, -0.61, 181.847),
                                                                                SetAttachOffset(0.0, 0.0, 0.0),
                                                                                SetSkinWeight(0, 30.000001192092896),
                                                                                SetSkinWeight(2, 30.000001192092896),
                                                                                SetSkinWeight(3, 30.000001192092896),
                                                                                SetSkinWeight(4, 69.9999988079071),
                                                                                SetSkinWeight(5, 50.0),
                                                                                SetSkinWeight(6, 100.0),
                                                                                SetSkinWeight(7, 100.0),
                                                                                SetSkinWeight(8, 80.0000011920929),
                                                                                SetSkinWeight(10, 20.000000298023224),
                                                                                SetSkinWeight(11, 20.000000298023224),
                                                                                SetSkinWeight(12, 30.000001192092896),
                                                                                SetSkinWeight(13, 20.000000298023224),
                                                                                SetSkinWeight(14, 20.000000298023224),
                                                                                SetSkinWeight(15, 69.9999988079071),
                                                                                SetSkinWeight(16, 80.0000011920929),
                                                                                SetSkinWeight(17, 100.0),
                                                                                SetSkinWeight(18, 40.00000059604645),
                                                                                SetSkinWeight(19, 69.9999988079071),
                                                                                SetSkinWeight(20, 80.0000011920929),
                                                                                SetSkinWeight(21, 40.00000059604645),
                                                                                SetSkinWeight(22, 80.0000011920929),
                                                                                SetSkinWeight(23, 60.00000238418579),
                                                                                SetSkinWeight(24, 100.0),
                                                                                SetSkinWeight(25, 40.00000059604645),
                                                                                MakeAttachedJoint(DYNOBJ_MARIO_LEFT_EYEBROW_MPART_JOINT_2),
                                                                                SetScale(1.0, 1.0, 1.0),
                                                                                SetRotation(0.0, 0.0, 0.0),
                                                                                SetAttachOffset(388.6, 0.0, 0.0),
                                                                                EndNetWithSubGroup(DYNOBJ_MARIO_LEFT_EYEBROW_MPART_SKIN_NET),
                                                                                MakeDynObj(D_NET, DYNOBJ_MARIO_MUSTACHE_NET),
                                                                                SetType(2),
                                                                                SetShapePtr(DYNOBJ_MARIO_MUSTACHE_SHAPE),
                                                                                AttachTo(13, DYNOBJ_MARIO_MAIN_NET),
                                                                                SetScale(1.0, 1.0, 1.0),
                                                                                SetRotation(0.02, -0.002, 0.04),
                                                                                SetAttachOffset(0.0, 0.0, 0.0),
                                                                                MakeNetWithSubGroup(DYNOBJ_MARIO_LEFT_MUSTACHE_SKIN_NET),
                                                                                    AttachTo(13, DYNOBJ_MARIO_MUSTACHE_NET),
                                                                                    SetSkinShape(DYNOBJ_MARIO_MUSTACHE_SHAPE),
                                                                                    SetScale(1.0, 1.0, 1.0),
                                                                                    SetRotation(0.0, 180.0, 0.0),
                                                                                    SetAttachOffset(4.2, -86.5, 415.5),
                                                                                    MakeAttachedJoint(DYNOBJ_MARIO_LEFT_MUSTACHE_JOINT_1),
                                                                                    SetScale(1.0, 1.0, 1.0),
                                                                                    SetRotation(-179.98, -164.53, -29.34),
                                                                                    SetAttachOffset(0.0, 0.0, 0.0),
                                                                                    SetSkinWeight(3, 50.0),
                                                                                    SetSkinWeight(4, 50.0),
                                                                                    SetSkinWeight(5, 50.0),
                                                                                    SetSkinWeight(11, 69.9999988079071),
                                                                                    SetSkinWeight(12, 80.0000011920929),
                                                                                    SetSkinWeight(13, 69.9999988079071),
                                                                                    SetSkinWeight(18, 80.0000011920929),
                                                                                    SetSkinWeight(19, 80.0000011920929),
                                                                                    SetSkinWeight(20, 80.0000011920929),
                                                                                    SetSkinWeight(21, 100.0),
                                                                                    SetSkinWeight(22, 100.0),
                                                                                    SetSkinWeight(23, 100.0),
                                                                                    SetSkinWeight(25, 100.0),
                                                                                    SetSkinWeight(27, 100.0),
                                                                                    SetSkinWeight(28, 50.0),
                                                                                    SetSkinWeight(29, 40.00000059604645),
                                                                                    SetSkinWeight(30, 40.00000059604645),
                                                                                    SetSkinWeight(31, 100.0),
                                                                                    SetSkinWeight(36, 50.0),
                                                                                    SetSkinWeight(37, 50.0),
                                                                                    SetSkinWeight(42, 40.00000059604645),
                                                                                    SetSkinWeight(45, 50.0),
                                                                                    SetSkinWeight(46, 50.0),
                                                                                    SetSkinWeight(47, 80.0000011920929),
                                                                                    SetSkinWeight(50, 40.00000059604645),
                                                                                    SetSkinWeight(51, 100.0),
                                                                                    SetSkinWeight(53, 40.00000059604645),
                                                                                    SetSkinWeight(54, 80.0000011920929),
                                                                                    MakeAttachedJoint(DYNOBJ_MARIO_LEFT_MUSTACHE_JOINT_2),
                                                                                    SetScale(1.0, 1.0, 1.0),
                                                                                    SetRotation(-0.028, 0.0, 0.02),
                                                                                    SetAttachOffset(292.7, 0.0, 0.0),
                                                                                    EndNetWithSubGroup(DYNOBJ_MARIO_LEFT_MUSTACHE_SKIN_NET),
                                                                                    MakeNetWithSubGroup(DYNOBJ_MARIO_RIGHT_MUSTACHE_SKIN_NET),
                                                                                        AttachTo(13, DYNOBJ_MARIO_MUSTACHE_NET),
                                                                                        SetSkinShape(DYNOBJ_MARIO_MUSTACHE_SHAPE),
                                                                                        SetScale(1.0, 1.0, 1.0),
                                                                                        SetRotation(0.0, 0.0, 0.0),
                                                                                        SetAttachOffset(-4.2, -86.5, 415.5),
                                                                                        MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_MUSTACHE_JOINT_1),
                                                                                        SetScale(1.0, 1.0, 1.0),
                                                                                        SetRotation(0.0, 15.47, 150.66),
                                                                                        SetAttachOffset(0.0, 0.0, 0.0),
                                                                                        SetSkinWeight(0, 100.0),
                                                                                        SetSkinWeight(1, 80.0000011920929),
                                                                                        SetSkinWeight(2, 80.0000011920929),
                                                                                        SetSkinWeight(6, 100.0),
                                                                                        SetSkinWeight(7, 100.0),
                                                                                        SetSkinWeight(8, 50.0),
                                                                                        SetSkinWeight(9, 50.0),
                                                                                        SetSkinWeight(10, 50.0),
                                                                                        SetSkinWeight(14, 50.0),
                                                                                        SetSkinWeight(15, 50.0),
                                                                                        SetSkinWeight(16, 50.0),
                                                                                        SetSkinWeight(17, 80.0000011920929),
                                                                                        SetSkinWeight(24, 100.0),
                                                                                        SetSkinWeight(26, 100.0),
                                                                                        SetSkinWeight(32, 80.0000011920929),
                                                                                        SetSkinWeight(33, 100.0),
                                                                                        SetSkinWeight(34, 69.9999988079071),
                                                                                        SetSkinWeight(35, 50.0),
                                                                                        SetSkinWeight(38, 40.00000059604645),
                                                                                        SetSkinWeight(39, 40.00000059604645),
                                                                                        SetSkinWeight(40, 40.00000059604645),
                                                                                        SetSkinWeight(41, 50.0),
                                                                                        SetSkinWeight(43, 50.0),
                                                                                        SetSkinWeight(44, 50.0),
                                                                                        SetSkinWeight(48, 80.0000011920929),
                                                                                        SetSkinWeight(49, 69.9999988079071),
                                                                                        SetSkinWeight(52, 40.00000059604645),
                                                                                        SetSkinWeight(55, 80.0000011920929),
                                                                                        MakeAttachedJoint(DYNOBJ_MARIO_RIGHT_MUSTACHE_JOINT_2),
                                                                                        SetScale(1.0, 1.0, 1.0),
                                                                                        SetRotation(0.0, 0.0, 0.0),
                                                                                        SetAttachOffset(292.7, 0.0, 0.0),
                                                                                        EndNetWithSubGroup(DYNOBJ_MARIO_RIGHT_MUSTACHE_SKIN_NET),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_RIGHT_MUSTACHE_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_mustache_right),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_RIGHT_MUSTACHE_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_RIGHT_MUSTACHE_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_RIGHT_MUSTACHE_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_LEFT_MUSTACHE_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_mustache_left),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_LEFT_MUSTACHE_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_LEFT_MUSTACHE_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_LEFT_MUSTACHE_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, 32),
                                                                                        LinkWithPtr(&anim_mario_lips_1),
                                                                                        MakeDynObj(D_ANIMATOR, 33),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(32),
                                                                                        LinkWith(DYNOBJ_MARIO_LEFT_EYEBROW_MPART_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, 41),
                                                                                        LinkWithPtr(&anim_mario_lips_2),
                                                                                        MakeDynObj(D_ANIMATOR, 42),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(41),
                                                                                        LinkWith(DYNOBJ_MARIO_LEFT_EYEBROW_RPART_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, 50),
                                                                                        LinkWithPtr(&anim_mario_eyebrows_1),
                                                                                        MakeDynObj(D_ANIMATOR, 51),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(50),
                                                                                        LinkWith(DYNOBJ_MARIO_LEFT_EYEBROW_LPART_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, 63),
                                                                                        LinkWithPtr(&anim_mario_eyebrows_equalizer),
                                                                                        MakeDynObj(D_ANIMATOR, 64),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(63),
                                                                                        LinkWith(DYNOBJ_MARIO_RIGHT_EYEBROW_MPART_JOINT_2),
                                                                                        MakeDynObj(D_DATA_GRP, 66),
                                                                                        LinkWithPtr(&anim_mario_eyebrows_2),
                                                                                        MakeDynObj(D_ANIMATOR, 67),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(66),
                                                                                        LinkWith(DYNOBJ_MARIO_RIGHT_EYEBROW_MPART_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, 72),
                                                                                        LinkWithPtr(&anim_mario_eyebrows_3),
                                                                                        MakeDynObj(D_ANIMATOR, 73),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(72),
                                                                                        LinkWith(DYNOBJ_MARIO_RIGHT_EYEBROW_LPART_JOINT_2),
                                                                                        MakeDynObj(D_DATA_GRP, 75),
                                                                                        LinkWithPtr(&anim_mario_eyebrows_4),
                                                                                        MakeDynObj(D_ANIMATOR, 76),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(75),
                                                                                        LinkWith(DYNOBJ_MARIO_RIGHT_EYEBROW_LPART_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, 84),
                                                                                        LinkWithPtr(&anim_mario_eyebrows_5),
                                                                                        MakeDynObj(D_ANIMATOR, 85),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(84),
                                                                                        LinkWith(DYNOBJ_MARIO_RIGHT_EYEBROW_RPART_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_LEFT_EYE_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_eye_left),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_LEFT_EYE_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_LEFT_EYE_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_LEFT_EYE_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_RIGHT_EYE_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_eye_right),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_RIGHT_EYE_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_RIGHT_EYE_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_RIGHT_EYE_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_CAP_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_cap),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_CAP_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_CAP_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_CAP_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_LEFT_LIP_CORNER_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_lips_3),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_LEFT_LIP_CORNER_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_LEFT_LIP_CORNER_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_LEFT_LIP_CORNER_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_RIGHT_LIP_CORNER_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_lips_4),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_RIGHT_LIP_CORNER_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_RIGHT_LIP_CORNER_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_RIGHT_LIP_CORNER_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_LEFT_EAR_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_ear_left),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_LEFT_EAR_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_LEFT_EAR_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_LEFT_EAR_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_RIGHT_EAR_ANIMADATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_ear_right),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_RIGHT_EAR_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_RIGHT_EAR_ANIMADATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_RIGHT_EAR_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_NOSE_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_nose),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_NOSE_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_NOSE_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_NOSE_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_LEFT_JAW_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_lips_5),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_LEFT_JAW_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_LEFT_JAW_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_LEFT_JAW_JOINT),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_RIGHT_JAW_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_lips_6),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_RIGHT_JAW_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_RIGHT_JAW_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_RIGHT_JAW_JOINT),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_LEFT_EYELID_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_eyelid_left),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_LEFT_EYELID_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_LEFT_EYELID_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_LEFT_EYELID_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_RIGHT_EYELID_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_eyelid_right),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_RIGHT_EYELID_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_RIGHT_EYELID_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_RIGHT_EYELID_JOINT_1),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_MARIO_HEAD_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_mario_intro),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_MARIO_HEAD_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_MARIO_HEAD_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_MARIO_MAIN_NET),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_SILVER_STAR_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_silver_star),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_SILVER_STAR_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_SILVER_STAR_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_SILVER_STAR_LIGHT),
                                                                                        MakeDynObj(D_DATA_GRP, DYNOBJ_RED_STAR_ANIMDATA_GROUP),
                                                                                        LinkWithPtr(&anim_red_star),
                                                                                        MakeDynObj(D_ANIMATOR, DYNOBJ_RED_STAR_ANIMATOR),
                                                                                        AttachTo(0, DYNOBJ_MARIO_MAIN_ANIMATOR),
                                                                                        SetNodeGroup(DYNOBJ_RED_STAR_ANIMDATA_GROUP),
                                                                                        LinkWith(DYNOBJ_RED_STAR_LIGHT),
                                                                                    EndGroup(1),
                                                                                    UseObj(1),
                                                                                    UseIntegerNames(FALSE),
                                                                                    EndList(),
};
